spring.application.name=Android
server.address=0.0.0.0
server.port=8181

# MySQL
spring.datasource.url=jdbc:mysql://${MYSQL_HOST:localhost}:3306/db_android
spring.datasource.username=root
spring.datasource.password=Manuel1921@
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver